# docker-compose up --build

version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: ken
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: odyssey
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    networks:
      - cosmos-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ken -d odyssey"]
      interval: 10s
      timeout: 5s
      retries: 5

  core:
    image: estken/cosmos-odyssey-core:latest
    container_name: cosmos-odyssey-core
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 9090
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ken
      DB_PASSWORD: pass
      DB_NAME: odyssey
    ports:
      - "9090:9090"
    restart: always
    networks:
      - cosmos-network

  frontend:
    image: estken/cosmos-odyssey-frontend:latest
    container_name: cosmos-odyssey-frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - cosmos-network
      
volumes:
  postgres-data:

networks:
  cosmos-network: